### ISSUE TITLE
no-trailing-spaces

### ISSUE THREAD

**Issue by aliasmrchips** [descarteslabs/pizzazz#4]
Can we add an exception to the no-trailing-spaces rule for blank lines? I think `"skipBlankLines": true` would work

**Comment by sunny-g** [comment]
Why do you want to skip blank lines? It seems to me that doing so would pollute commits, especially among editors that handle trailing spaces differently.

**Comment by aliasmrchips** [comment]
My understanding of the option is that it would allow for trailing spaces on blank lines. I ask for it because I am constantly doing it. I don't see the downside, but interested to hear another opinion. Maybe I like whitespace too much.

**Comment by sunny-g** [comment]
Correct, that's what it would allow, but my editors automatically strip extraneous whitespace (I think it's just a checkbox in c9), so if we we're collaborating on a project, we'd end up getting a lot of commits adding and removing whitespace on empty lines over and over again.

Would you mind giving this a shot and seeing if it works for you? https://stackoverflow.com/questions/27881197/how-do-i-strip-trailing-whitespace-before-each-save-in-cloud9

**Comment by aliasmrchips** [comment]
Sounds good... you win this round Mr Gonnabathula
